// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"

	"github.com/shopspring/decimal"
)

type Account struct {
	ID        int64           `json:"id"`
	CreatedAt sql.NullTime    `json:"created_at"`
	UpdatedAt sql.NullTime    `json:"updated_at"`
	DeletedAt sql.NullTime    `json:"deleted_at"`
	Owner     string          `json:"owner"`
	Currency  string          `json:"currency"`
	Balance   decimal.Decimal `json:"balance"`
}

type Entry struct {
	ID         int64           `json:"id"`
	CreatedAt  sql.NullTime    `json:"created_at"`
	UpdatedAt  sql.NullTime    `json:"updated_at"`
	DeletedAt  sql.NullTime    `json:"deleted_at"`
	AccountsID int64           `json:"accounts_id"`
	Amount     decimal.Decimal `json:"amount"`
}

type Transfer struct {
	ID            int64           `json:"id"`
	CreatedAt     sql.NullTime    `json:"created_at"`
	UpdatedAt     sql.NullTime    `json:"updated_at"`
	DeletedAt     sql.NullTime    `json:"deleted_at"`
	FromAccountID int64           `json:"from_account_id"`
	ToAccountID   int64           `json:"to_account_id"`
	Amount        decimal.Decimal `json:"amount"`
}
